Repository Hilistia/smp, pull requests merged in 2024-12, with the labels that each got.

#21 docs: update readme for merged project
  README.md
Labels: documentation

#24 fix: limit mutandis to vanilla items + own mod
  world/datapacks/hilistia/data/enchanted/tags/blocks/mutandis_extremis_plants.json
  world/datapacks/hilistia/data/enchanted/tags/blocks/mutandis_plants.json
Labels: bug

#34 fix: remove shapeless rope and nail recipe via new reciperemover mod
  config/reciperemover.json
Labels: bug

#35 feat: adjust levelz for spectrum
  world/datapacks/hilistia/data/levelz/mining/spectrum_adjustments.json
Labels: enhancement

#36 feat: add new mod configs
  config/amendments-common.json
  config/handoveryouritems.json5
  config/pottery-client.toml
  config/sawmill-common.json
  config/tradingpost-server.toml
Labels: enhancement

#40 feat: add barkling gided oak saplings to saplings tag
  world/datapacks/hilistia/data/minecraft/tags/blocks/saplings.json
Labels: enhancement

#45 Remove Crafting Recipes Shipping Container
  config/reciperemover.json
Labels: enhancement, build-ready

#53 added season compat for Spectrum
  world/datapacks/hilistia/data/spectrum/seasons/crop/amaranth.json
  world/datapacks/hilistia/data/spectrum/seasons/crop/black_sapling.json
  world/datapacks/hilistia/data/spectrum/seasons/crop/blue_sapling.json
  world/datapacks/hilistia/data/spectrum/seasons/crop/brown_sapling.json
  world/datapacks/hilistia/data/spectrum/seasons/crop/cyan_sapling.json
  world/datapacks/hilistia/data/spectrum/seasons/crop/glistering_melon_stem.json
  world/datapacks/hilistia/data/spectrum/seasons/crop/gray_sapling.json
  world/datapacks/hilistia/data/spectrum/seasons/crop/green_saplin.json
  world/datapacks/hilistia/data/spectrum/seasons/crop/light_blue_sapling.json
  world/datapacks/hilistia/data/spectrum/seasons/crop/light_gray_sapling.json
  world/datapacks/hilistia/data/spectrum/seasons/crop/lime_sapling.json
  world/datapacks/hilistia/data/spectrum/seasons/crop/magenta_sapling.json
  world/datapacks/hilistia/data/spectrum/seasons/crop/orange_sapling.json
  world/datapacks/hilistia/data/spectrum/seasons/crop/pink_sapling.json
  world/datapacks/hilistia/data/spectrum/seasons/crop/purple_sapling.json
  world/datapacks/hilistia/data/spectrum/seasons/crop/red_sapling.json
  world/datapacks/hilistia/data/spectrum/seasons/crop/weeping_gala_sprig.json
  world/datapacks/hilistia/data/spectrum/seasons/crop/white_sapling.json
  world/datapacks/hilistia/data/spectrum/seasons/crop/yellow_sapling.json
Labels: build-ready

#63 feat: add afk plus config
  config/afkplus.json
  config/more-color-api.json
Labels: enhancement

#70 fix: adjust afk config per spec
  config/afkplus.json
Labels: bug

#69 fix: update season duration values
  config/seasons.json
Labels: bug, accepted
